/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:12b3b09e-34eb-4e29-a66e-cd82cc406e90",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HeiYGTYbf",
    "aws_user_pools_web_client_id": "77v3mia054cftgle91pltvbrug",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fsbz7h7r7bftjd4zl47t5d363y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lf5bfzrdb5hdpna6xhu7rbcl5q"
};


export default awsmobile;
