/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:12b3b09e-34eb-4e29-a66e-cd82cc406e90",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HeiYGTYbf",
    "aws_user_pools_web_client_id": "77v3mia054cftgle91pltvbrug",
    "oauth": {}
};


export default awsmobile;
